### ISSUE TITLE
Add required Python 2 modules

### ISSUE THREAD

**Issue by iLLiCiTiT** [pypeclub/OpenPype#1291]
## Issue
- there are some Python modules that are not available in Python 2 hosts but are required for work
- Maya/Nuke can't connect to cloud mongo because of `dnspython` module
<details><summary>Maya Traceback</summary>
<p>
<b>NOTE:</b> Stack trace is not relevant as we had to modify code to find out what is real issue.

```
Traceback (most recent call last):
  File "C:\Users\qam\pypeclub\pype3\pype\openpype\hosts\maya\startup\userSetup.py", line 10, in <module>
    settings = get_project_settings(os.environ['AVALON_PROJECT'])
  File "C:\Users\qam\pypeclub\pype3\pype\openpype\settings\lib.py", line 759, in get_project_settings
    studio_overrides = get_default_project_settings(False)
  File "C:\Users\qam\pypeclub\pype3\pype\openpype\settings\lib.py", line 674, in get_default_project_settings
    studio_values = get_studio_project_settings_overrides()
  File "C:\Users\qam\pypeclub\pype3\pype\openpype\settings\lib.py", line 46, in wrapper
    _SETTINGS_HANDLER = create_settings_handler()
  File "C:\Users\qam\pypeclub\pype3\pype\openpype\settings\lib.py", line 65, in create_settings_handler
    return MongoSettingsHandler()
  File "C:\Users\qam\pypeclub\pype3\pype\openpype\settings\handlers.py", line 176, in __init__
    settings_collection = OpenPypeMongoConnection.get_mongo_client()
  File "C:\Users\qam\pypeclub\pype3\pype\openpype\lib\mongo.py", line 159, in get_mongo_client
    connection = cls.create_connection(mongo_url)
  File "C:\Users\qam\pypeclub\pype3\pype\openpype\lib\mongo.py", line 178, in create_connection
    mongo_client = pymongo.MongoClient(**kwargs)
  File "C:\Users\qam\pypeclub\pype3\pype\.venv\lib\site-packages\pymongo\mongo_client.py", line 641, in __init__
    connect_timeout=timeout)
  File "C:\Users\qam\pypeclub\pype3\pype\.venv\lib\site-packages\pymongo\uri_parser.py", line 428, in parse_uri
    raise ConfigurationError('The "dnspython" module must be '
ConfigurationError: The "dnspython" module must be installed to use mongodb+srv:// URIs
```
</p>
</details>

- Houdini with Python 2 can't import `pymongo` because has issue with syntax error in `dns` module (`pymongo` catch only `ImportError` )
<details><summary>Houdini Python 2 Traceback</summary>
<p>
<b>NOTE:</b> Stack trace is not relevant as we had to modify code to find out what is real issue.

```
Traceback (most recent call last):
  File "C:/Users/qam/pypeclub/pype3/pype/openpype/hosts/houdini/startup/scripts/123.py", line 1, in <module>
    from avalon import api, houdini
  File "C:\Users\qam\pypeclub\pype3\pype\repos\avalon-core\avalon\api.py", line 13, in <module>
    from . mongodb import (
  File "C:\Users\qam\pypeclub\pype3\pype\repos\avalon-core\avalon\mongodb.py", line 6, in <module>
    import pymongo
  File "C:\Users\qam\pypeclub\pype3\pype\.venv\lib\site-packages\pymongo\__init__.py", line 91, in <module>
    from pymongo.mongo_client import MongoClient
  File "C:\Users\qam\pypeclub\pype3\pype\.venv\lib\site-packages\pymongo\mongo_client.py", line 46, in <module>
    from pymongo import (common,
  File "C:\Users\qam\pypeclub\pype3\pype\.venv\lib\site-packages\pymongo\uri_parser.py", line 31, in <module>
    from pymongo.srv_resolver import _HAVE_DNSPYTHON, _SrvResolver
  File "C:\Users\qam\pypeclub\pype3\pype\.venv\lib\site-packages\pymongo\srv_resolver.py", line 18, in <module>
    from dns import resolver
  File "C:\Users\qam\pypeclub\pype3\pype\.venv\lib\site-packages\dns\resolver.py", line 31, in <module>
    import dns.exception
  File "C:\Users\qam\pypeclub\pype3\pype\.venv\lib\site-packages\dns\exception.py", line 141
    raise self.exception_class(str(exc_val)) from exc_val
                                                ^
SyntaxError: invalid syntax
```
</p>
</details>

**Comment by mkolar** [comment]
resolved in https://github.com/pypeclub/OpenPype/pull/1354
