### ISSUE TITLE
Maya: RedshiftOptions.imageFormat is not an enum attribute

### ISSUE THREAD

**Issue by BigRoy** [pypeclub/OpenPype#1685]
**Describe the bug**

The [method to query the file extension for Redshift](https://github.com/pypeclub/OpenPype/blob/aaf8048eb883733d9679915a70049d50440cdb8c/openpype/hosts/maya/api/expected_files.py#L802-L803) fails on my machine due to it not being an enum attribute.

So this:
```python
default_ext = cmds.getAttr("redshiftOptions.imageFormat", asString=True)
# 0
```
Actually returns an integer for me.
Apparently Maya doesn't consider it to be an enum.
```python
print cmds.attributeQuery("imageFormat", node="redshiftOptions", enum=True)
# False
print cmds.attributeQuery("imageFormat", node="redshiftOptions", listEnum=True)
# None
```

I'm not actually running OpenPype so I can not confirm this actually results in an issue for OpenPype, but looking at the code I assume it would.

**Desktop:**
 - OS: Windows 10
 - Host: Maya 2020.4
 - Redshift 3.0.31 + updated to 3.0.45 after, same issue.

---
Redshift seems to do this internally in `C:\ProgramData\Redshift\Plugins\Maya\Common\scripts\redshiftGetImageExtension.mel`, see details: 

<details>

```
global proc string redshiftGetImageExtension(int $imageFormat)
{
	redshiftCreateImageFormats();
	global string $g_redshiftImageFormatExtensions[];
	
	return $g_redshiftImageFormatExtensions[$imageFormat];
}
```
With `redshiftCreateImageFormats` being:
```
global proc redshiftCreateImageFormats()
{
	global string $g_redshiftImageFormatExtensions[];
	global string $g_redshiftImageFormatLabels[];
	
	$g_redshiftImageFormatExtensions[0] = "iff";
	$g_redshiftImageFormatExtensions[1] = "exr";
	$g_redshiftImageFormatExtensions[2] = "png";
	$g_redshiftImageFormatExtensions[3] = "tga";
	$g_redshiftImageFormatExtensions[4] = "jpg";
	$g_redshiftImageFormatExtensions[5] = "tif";
	$g_redshiftImageFormatExtensions[6] = "exr";
	
	$g_redshiftImageFormatLabels[0] = "Maya IFF (iff)";
	$g_redshiftImageFormatLabels[1] = "OpenEXR (exr)";
	$g_redshiftImageFormatLabels[2] = "PNG (png)";
	$g_redshiftImageFormatLabels[3] = "Targa (tga)";
	$g_redshiftImageFormatLabels[4] = "JPEG (jpg)";
	$g_redshiftImageFormatLabels[5] = "TIFF (tif)";
	$g_redshiftImageFormatLabels[6] = "Cryptomatte (exr)";
}
```
</details>

**Comment by BigRoy** [comment]
Actually, seems even with that fixed `ExpectedFilesRedshift` will also still bug out on [this line](https://github.com/pypeclub/OpenPype/blob/aaf8048eb883733d9679915a70049d50440cdb8c/openpype/hosts/maya/api/expected_files.py#L754) with error:
```python
# Traceback (most recent call last):
#   File "<maya console>", line 13, in <module>
#   File "expected_files.py", line 151, in get
#     layer, self._render_instance))
#   File "expected_files.py", line 165, in _get_files
#     files = renderer.get_files()
#   File "expected_files.py", line 768, in get_files
#     if layer_data.get("enabledAOVs"):
# AttributeError: 'LayerMetadata' object has no attribute 'get' # 
```
