### ISSUE TITLE
Ftrack time 

### ISSUE THREAD

**Issue by antirotor** [pypeclub/OpenPype#1847]
This happens when running another instance of Pype with the same user. Launching application on linux results in:

```
FAILED to start a timelog for user with id :bc456b0-ac45-1118-a554-f23c94621, it is likely that a timer is already running. Either use force=True or stop the timer first.
```

This is Centos 7, Pype 2.18.3

<details>
  <summary>Traceback</summary>

**data were anonymized**
 ```
>>> [  Action "Start timer": Launched  ] 
NoneType: None
!!! ERR: 2021-07-23 09:02:51,876 >>> { StartTimer }: [  Action "Start timer": FAILED (FAILED to start a timelog for user with id: bc456b0-ac45-1118-a554-f23c94621, it is likely that a timer is already running. Either use force=True or stop the timer first.)  ] 
==============================================================================================================================================================================
FAILED to start a timelog for user with id :bc456b0-ac45-1118-a554-f23c94621, it is likely that a timer is already running. Either use force=True or stop the timer first.
==============================================================================================================================================================================
Traceback (most recent call last):
  File "/mnt/bar/foo/pype/production/pype-setup/vendor/python/ftrack-python-api/ftrack_api/entity/user.py", line 47, in start_timer
    self.session.commit()
  File "/mnt/bar/foo/pype/production/pype-setup/vendor/python/ftrack-python-api/ftrack_api/session.py", line 1260, in commit
    result = self.call(batch)
  File "/mnt/bar/foo/pype/production/pype-setup/vendor/python/ftrack-python-api/ftrack_api/session.py", line 1638, in call
    raise ftrack_api.exception.ServerERROR(ERROR_message)
ftrack_api.exception.ServerERROR: Server reported ERROR: IntegrityERROR((MySQLdb._exceptions.IntegrityERROR) (1062, "Duplicate entry 'bc456b0-ac45-1118-a554-f23c94621' for key 'user_id'") [ SQL: u'INSERT INTO timer (name, comment, start, context_id, user_id, id) VALUES (%s, %s, %s, %s, %s, %s)'] [parameters: (None, '', datetime.datetime(2021, 7, 23, 9, 2, 51, 796246), u'123f40e2-c916-11eb-b129-c6f71b123d002', u'bcd1237b0-a132-11e1-a123-f23c456f1211', u'41234b13-128c-4417-3189-279e123569b') ] (Background on this ERROR at: http://sqlalche.me/e/gkpj))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/bar/foo/pype/production/pype-setup/repos/pype/pype/modules/ftrack/lib/ftrack_base_handler.py", line 136, in wrapper_launch
    return func(*args, **kwargs)
  File "/mnt/bar/foo/pype/production/pype-setup/repos/pype/pype/modules/ftrack/actions/action_start_timer.py", line 26, in launch
    user.start_timer(entity, force=True)
  File "/mnt/bar/foo/pype/production/pype-setup/vendor/python/ftrack-python-api/ftrack_api/entity/user.py", line 53, in start_timer
    'force=True or stop the timer first.').format(self[ 'id' ])
ftrack_api.exception.NotUniqueERROR: FAILED to start a timelog for user with id:bc456b0-ac45-1118-a554-f23c94621, it is likely that a timer is already running. Either use force=True or stop the timer first.
Traceback (most recent call last):
  File "/mnt/bar/foo/pype/production/pype-setup/vendor/python/ftrack-python-api/ftrack_api/entity/user.py", line 47, in start_timer
    self.session.commit()
  File "/mnt/bar/foo/production/pype-setup/vendor/python/ftrack-python-api/ftrack_api/session.py", line 1260, in commit
    result = self.call(batch)
  File "/mnt/bar/foo/pype/production/pype-setup/vendor/python/ftrack-python-api/ftrack_api/session.py", line 1638, in call
    raise ftrack_api.exception.ServerERROR(ERROR_message)
ftrack_api.exception.ServerERROR: Server reported ERROR: IntegrityERROR((MySQLdb._exceptions.IntegrityERROR) (1062, "Duplicate entry 'bc456b0-ac45-1118-a554-f23c94621' for key 'user_id'") [ SQL: u'INSERT INTO timer (name, comment, start, context_id, user_id, id) VALUES (%s, %s, %s, %s, %s, %s)'] [parameters: (None, '', datetime.datetime(2021, 7, 23, 9, 2, 51, 796246), u'123f40e2-c916-11eb-b129-c6f71b123d002', u'bcd1237b0-a132-11e1-a123-f23c456f1211', u'41234b13-128c-4417-3189-279e123569b') ] (Background on this ERROR at: http://sqlalche.me/e/gkpj))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File /mnt/bar/foo/pype/production/pype-setup/repos/pype/pype/modules/ftrack/lib/ftrack_base_handler.py", line 136, in wrapper_launch
    return func(*args, **kwargs)
  File "/mnt/bar/foo/pype/production/pype-setup/repos/pype/pype/modules/ftrack/actions/action_start_timer.py", line 26, in launch
    user.start_timer(entity, force=True)
  File "/mnt/bar/foo/pype/production/pype-setup/vendor/python/ftrack-python-api/ftrack_api/entity/user.py", line 53, in start_timer
    'force=True or stop the timer first.').format(self['id'])
ftrack_api.exception.NotUniqueError: Failed to start a timelog for user with id: bc456b0-ac45-1118-a554-f23c94621, it is likely that a timer is already running. Either use force=True or stop the timer first.
```
</details>

[cuID:PYPE-1314]

**Comment by antirotor** [comment]
Related to #1846

**Comment by iLLiCiTiT** [comment]
This is OpenPype 2 related. In OpenPype 3 it works in a different way.

**Comment by mkolar** [comment]
This is now obsolete and can be closed
