### ISSUE TITLE
Maya: Extract Look Spaces in Filename

### ISSUE THREAD

**Issue by tokejepsen** [pypeclub/OpenPype#2055]
**Describe the bug**
Extractor errors when there is a space in the name of a file when creating the tx files.

**To Reproduce**
1. Publish a look with a file that has spaces in the name.

Spaces are generally bad, so maybe we should have a validator that replaces the spaces in the names with `_`?

[cuID:PYPE-1916]

**Comment by BigRoy** [comment]
To reproduce the error:
```python
import os


# copied from openpype/hosts/maya/plugins/publish/extract_look.py
def maketx(source, destination, *args):
    """Make `.tx` using `maketx` with some default settings.

    The settings are based on default as used in Arnold's
    txManager in the scene.
    This function requires the `maketx` executable to be
    on the `PATH`.

    Args:
        source (str): Path to source file.
        destination (str): Writing destination path.
        *args: Additional arguments for `maketx`.

    Returns:
        str: Output of `maketx` command.

    """
    from openpype.lib import get_oiio_tools_path

    maketx_path = get_oiio_tools_path("maketx")

    if platform.system().lower() == "windows":
        # Ensure .exe extension
        maketx_path += ".exe"

    if not os.path.exists(maketx_path):
        print(
            "OIIO tool not found in {}".format(maketx_path))
        raise AssertionError("OIIO tool not found")

    cmd = [
        maketx_path,
        "-v",  # verbose
        "-u",  # update mode
        # unpremultiply before conversion (recommended when alpha present)
        "--unpremult",
        "--checknan",
        # use oiio-optimized settings for tile-size, planarconfig, metadata
        "--oiio",
        "--filter lanczos3",
    ]

    cmd.extend(args)
    cmd.extend(["-o", destination, source])

    cmd = " ".join(cmd)

    CREATE_NO_WINDOW = 0x08000000  # noqa
    kwargs = dict(args=cmd, stderr=subprocess.STDOUT, shell=True)

    if sys.platform == "win32":
        kwargs["creationflags"] = CREATE_NO_WINDOW
    try:
        out = subprocess.check_output(**kwargs)
    except subprocess.CalledProcessError as exc:
        print(exc)
        import traceback

        traceback.print_exc()
        raise

    return out

texture = r"S:\texture space.png"
maketx(texture, texture.replace(".png", ".tx"))
```

The error:
```python
# Error: Command 'S:\openpype\OpenPype\vendor\bin\oiio\windows\maketx.exe -v -u --unpremult --checknan --oiio --filter lanczos3 -o S:\texture space.tx S:\texture space.png' returned non-zero exit status 1.
# Traceback (most recent call last):
#   File "<maya console>", line 18, in <module>
#   File "<maya console>", line 13, in maketx
#   File "S:\openpype\OpenPype\openpype\hosts/maya/plugins/publish/extract_look.py", line 95, in maketx
#     out = subprocess.check_output(**kwargs)
#   File "C:\Program Files\Autodesk\Maya2022\Python37\lib\subprocess.py", line 411, in check_output
#     **kwargs).stdout
#   File "C:\Program Files\Autodesk\Maya2022\Python37\lib\subprocess.py", line 512, in run
#     output=stdout, stderr=stderr)
# subprocess.CalledProcessError: Command 'S:\openpype\OpenPype\vendor\bin\oiio\windows\maketx.exe -v -u --unpremult --checknan --oiio --filter lanczos3 -o S:\texture space.tx S:\texture space.png' returned non-zero exit status 1. # 
```

The fix would be to enclose the paths in quotes, e.g. adding this makes it work:
```python 
    def _escape(path):
        # Ensure path is enclosed by quotes
        # to allow paths with spaces
        return '"{}"'.format(path)

    cmd.extend(args)
    cmd.extend(["-o", _escape(destination), _escape(source)])
```

**Comment by BigRoy** [comment]
An artist just hit this issue in a project - so I had to patch this up and test it here. Code is in #2518
