### ISSUE TITLE
PS webpublishing fails on second batch

### ISSUE THREAD

**Issue by kalisp** [pypeclub/OpenPype#2229]
```
!!! OpenPype crashed:
Traceback (most recent call last):
  File "start.py", line 1070, in boot
  File "c:\Program Files (x86)\OpenPype\dependencies\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\Program Files (x86)\OpenPype\dependencies\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\Program Files (x86)\OpenPype\dependencies\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\Program Files (x86)\OpenPype\dependencies\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\Program Files (x86)\OpenPype\dependencies\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\pypeclub\AppData\Local\pypeclub\openpype\openpype-v3.6.0-nightly.1\openpype\cli.py", line 178, in remotepublishfromapp
    targets=targets)
  File "C:\Users\pypeclub\AppData\Local\pypeclub\openpype\openpype-v3.6.0-nightly.1\openpype\pype_commands.py", line 162, in remotepublishfromapp
    "Cannot parse batch meta in {} folder".format(batch_dir))
ValueError: Cannot parse batch meta in W:\d2b6a078-53fd-43d9-be8d-b48bb2805c8e folder
```

[cuID:1rgp802]

**Comment by kalisp** [comment]
Closed by https://github.com/pypeclub/OpenPype/pull/2237
