### ISSUE TITLE
Maya: Setting colorspace fails in 2022

### ISSUE THREAD

**Issue by antirotor** [pypeclub/OpenPype#2352]
## Bug

When initializing scene in Maya 2022, setting of colorspace fails with:

```
# openpype.hosts.maya.api.lib : Setting scene resolution to: 1920 x 1080 # 
# Warning: avalon.pipeline : Traceback (most recent call last):
  File "E:\projects\openpype\3x\repos\avalon-core\avalon\pipeline.py", line 631, in emit
    callback(*args)
  File "E:\projects\openpype\3x\openpype\hosts\maya\api\__init__.py", line 199, in on_new
    lib.set_context_settings()
  File "E:\projects\openpype\3x\openpype\hosts\maya\api\lib.py", line 1917, in set_context_settings
    set_colorspace()
  File "E:\projects\openpype\3x\openpype\hosts\maya\api\lib.py", line 2818, in set_colorspace
    cmds.colorManagementPrefs(e=True, renderingSpaceName=renderSpace)
RuntimeError: colorManagementPrefs: Rendering space scene-linear Rec 709/sRGB is unknown.
```

[cuID:1vx7dva]

**Comment by antirotor** [comment]
Duplicate of #2454
