### ISSUE TITLE
Blender 3.0: OP is not integrated

### ISSUE THREAD

**Issue by 64qam** [pypeclub/OpenPype#2376]
When launching Blender 3.0,  OpenPype menu is not integrated into there

```
*** WRN: >>> { openpype.lib.import_utils }: [  Path not existing: `C:\Program Files (x86)\OpenPype\hosts\blender\vendor\opentimelineio`  ]
*** WRN: >>> { openpype.lib.import_utils }: [  Path not existing: `C:\Program Files (x86)\OpenPype\hosts\blender\vendor\opentimelineio`  ]
Traceback (most recent call last):
  File "c:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\modules\bpy\utils\__init__.py", line 136, in _test_import
    mod = __import__(module_name)
  File "C:\Program Files (x86)\OpenPype\repos\avalon-core\setup\blender\startup\avalon_setup.py", line 1, in <module>
    from avalon import api, blender
  File "C:\Program Files (x86)\OpenPype\repos\avalon-core\avalon\blender\__init__.py", line 7, in <module>
    from .pipeline import (
  File "C:\Program Files (x86)\OpenPype\repos\avalon-core\avalon\blender\pipeline.py", line 15, in <module>
    from . import lib, ops
  File "C:\Program Files (x86)\OpenPype\repos\avalon-core\avalon\blender\ops.py", line 20, in <module>
    from ..vendor.Qt import QtWidgets, QtCore
  File "C:\Program Files (x86)\OpenPype\repos\avalon-core\avalon\vendor\Qt.py", line 1755, in <module>
    _install()
  File "C:\Program Files (x86)\OpenPype\repos\avalon-core\avalon\vendor\Qt.py", line 1719, in _install
    raise ImportError("No Qt binding were found.")
ImportError: No Qt binding were found.

```

[cuID:1wm4hbk]

**Comment by Tilix4** [comment]
I've tested with `3.8.0-nightly.5` and the menu is correctly integrated.

**Comment by iLLiCiTiT** [comment]
There is known issue that workfiles tool is crashing on save/open.

**Comment by Tilix4** [comment]
Then nothing can be done about it?

**Comment by BigRoy** [comment]
Wasn't this issue gone in Blender 3.0.1? @iLLiCiTiT should this be closed?

@Tilix4 are you having Blender 3+ issues that are blocking you in OpenPype?

**Comment by iLLiCiTiT** [comment]
The issue described here is resolved. There may be still issues with blender implementation but they are not just in v 3.
