### ISSUE TITLE
Maya2022: Failed to create Render Instance 

### ISSUE THREAD

**Issue by m-u-r-p-h-y** [pypeclub/OpenPype#2476]
Creating Render Instance in Maya 2022 fails with the following error
(OP 3.6.4)

`Traceback (most recent call last):
File "C:\Program Files (x86)\OpenPype\openpype\tools\creator\window.py", line 430, in _on_create
data={"variant": variant}
File "C:\Program Files (x86)\OpenPype\repos\avalon-core\avalon\pipeline.py", line 924, in create
instance = plugin.process()
File "", line 152, in process
File "C:\Program Files (x86)\OpenPype\repos\avalon-core\avalon\maya\pipeline.py", line 529, in process
lib.imprint(instance, self.data)
File "C:\Program Files (x86)\OpenPype\repos\avalon-core\avalon\maya\lib.py", line 234, in imprint
raise TypeError("Unsupported type: %r" % type(value))
TypeError: Unsupported type: `

[cuID:OP-2280]

**Comment by BigRoy** [comment]
Fixed by https://github.com/pypeclub/OpenPype/pull/2445 with commit https://github.com/pypeclub/OpenPype/commit/cb99b0acf791c970aeef7c04c1f01487f8e9f260
