### ISSUE TITLE
Maya2022: Collecting Yeti Rig Instance

### ISSUE THREAD

**Issue by m-u-r-p-h-y** [pypeclub/OpenPype#2477]
Collecting Yeti Rig instance in Maya2022 leads to an error
(OP 3.6.4, Yeti 4.1.0, Maya2022.3)

```
Instance: 
yetiRigMain
Message: 
module 'itertools' has no attribute 'izip'
Line: 
133
Traceback: 
Traceback (most recent call last):
  File "C:\Program Files (x86)\OpenPype\dependencies\pyblish\plugin.py", line 522, in __explicit_process
    runner(*args)
  File "C:\Program Files (x86)\OpenPype\openpype\hosts\maya\plugins\publish\collect_yeti_rig.py", line 32, in process
  File "C:\Program Files (x86)\OpenPype\openpype\hosts\maya\plugins\publish\collect_yeti_rig.py", line 80, in collect_input_connections
  File "C:\Program Files (x86)\OpenPype\openpype\hosts\maya\api\lib.py", line 133, in pairwise
    return itertools.izip(a, a)
AttributeError: module 'itertools' has no attribute 'izip'
```

[cuID:OP-2281]

**Comment by BigRoy** [comment]
Fixed in https://github.com/pypeclub/OpenPype/pull/2445 with commit https://github.com/pypeclub/OpenPype/pull/2445/commits/7cc091054957a9bc3cd6cdcdac4963ddc899aeb1
