### ISSUE TITLE
Maya: Extract playblast fail

### ISSUE THREAD

**Issue by m-u-r-p-h-y** [pypeclub/OpenPype#2561]
review publish in Maya fails with the following error:
(Maya2020, Maya2022, OP 3.7.0, OP 3.8.0.nightly.4)

```
 // pyblish.ExtractPlayblast : playblast path  c:\users\render~1.far\appdata\local\temp\pyblish_tmp_idopdz\reviewMain.####.jpg // 
// pyblish.ExtractPlayblast : filename c:\users\render~1.far\appdata\local\temp\pyblish_tmp_idopdz\reviewMain // 
// Error: pyblish.plugin : Traceback (most recent call last):
  File "D:\REPO\OpenPype\.venv\lib\site-packages\pyblish\plugin.py", line 522, in __explicit_process
    runner(*args)
  File "D:\REPO\OpenPype\openpype\hosts\maya\plugins\publish\extract_playblast.py", line 135, in process
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "D:\REPO\OpenPype\.venv\lib\site-packages\pyblish\plugin.py", line 522, in __explicit_process
    runner(*args)
  File "<string>", line 135, in process
TypeError: 'NoneType' object is not iterable // 
Processing Thumbnail
// pyblish.ExtractThumbnail : Extracting capture.. //
```

[cuID:237u3f8]

**Comment by m-u-r-p-h-y** [comment]
It seems the case is single frame review (which is still a valid request)

![image](https://user-images.githubusercontent.com/352795/150153251-cfce0f94-4876-45b7-8a9b-f49dd698ab4f.png)
