### ISSUE TITLE
Delete Old Versions relies on Ftrack session

### ISSUE THREAD

**Issue by BigRoy** [pypeclub/OpenPype#2801]
**Describe the bug**

The [Delete Old Versions library loader action tries to access ftrack](https://github.com/pypeclub/OpenPype/blob/a4b440d080a8a392aa26bf9e333baec20f735c9b/openpype/plugins/load/delete_old_versions.py#L375-L405) even when the Ftrack module is disabled.

**To Reproduce**
1. Disable Ftrack + set no valid ftrack urls
2. Run the delete old versions action
3. You will get some errors

**Expected behavior**

- Skip any Ftrack logic if module is disabled.

**Additional context**

Note that the logic is the same in the [Ftrack Delete Old Versions action](https://github.com/pypeclub/OpenPype/blob/a4b440d080a8a392aa26bf9e333baec20f735c9b/openpype/modules/default_modules/ftrack/event_handlers_user/action_delete_old_versions.py) and there's a lot of duplicated code. If possible it might be nice to unify the logic where possible so there's less duplicated code to maintain. 

I'm assuming the same might be true for parts of `delivery` action in Ftrack and the one in the Library Loader even though that logic at first sight looks much less alike.

**Comment by kaamaurice** [comment]
Hi !

Agreed ! I have issues with `delete_old_versions` in Blender 3.1 and Ftrack is disable and I don't want to use it.

I will propose a bugfix soon to skip Ftrack logic if module is disabled.

** To Reproduce **
- Load an asset in Blender 3.1 with the OpenPYPE loader tool.

## Traceback
```>>> [ *** FAILED to load 1 files
- /Volumes/D11-TRAVAIL/DEV/OpenPype/openpype/plugins/load/delete_old_versions.py
**********
Traceback (most recent call last):

  File "/Volumes/D11-TRAVAIL/DEV/OpenPype/openpype/lib/python_module_tools.py", line 92, in modules_from_path
    module = import_filepath(full_path, mod_name)

  File "/Volumes/D11-TRAVAIL/DEV/OpenPype/openpype/lib/python_module_tools.py", line 37, in import_filepath
    module_loader.exec_module(module)

  File "<frozen importlib._bootstrap_external>", line 883, in exec_module

  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed

  File "/Volumes/D11-TRAVAIL/DEV/OpenPype/openpype/plugins/load/delete_old_versions.py", line 7, in <module>
    import ftrack_api

  File "/Applications/Blender.3.1.2.app/Contents/Resources/3.1/python/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)

  File "/Volumes/D11-TRAVAIL/DEV/OpenPype/.venv/lib/python3.7/site-packages/ftrack_api/__init__.py", line 5, in <module>
    from .session import Session

  File "/Applications/Blender.3.1.2.app/Contents/Resources/3.1/python/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)

  File "/Volumes/D11-TRAVAIL/DEV/OpenPype/.venv/lib/python3.7/site-packages/ftrack_api/session.py", line 33, in <module>
    import ftrack_api.exception

  File "/Applications/Blender.3.1.2.app/Contents/Resources/3.1/python/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)

  File "/Volumes/D11-TRAVAIL/DEV/OpenPype/.venv/lib/python3.7/site-packages/ftrack_api/exception.py", line 8, in <module>
    import ftrack_api.entity.base

  File "/Applications/Blender.3.1.2.app/Contents/Resources/3.1/python/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)

  File "/Volumes/D11-TRAVAIL/DEV/OpenPype/.venv/lib/python3.7/site-packages/ftrack_api/entity/base.py", line 12, in <module>
    import ftrack_api.attribute

  File "/Applications/Blender.3.1.2.app/Contents/Resources/3.1/python/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)

  File "/Volumes/D11-TRAVAIL/DEV/OpenPype/.venv/lib/python3.7/site-packages/ftrack_api/attribute.py", line 14, in <module>
    import ftrack_api.collection

  File "/Applications/Blender.3.1.2.app/Contents/Resources/3.1/python/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)

  File "/Volumes/D11-TRAVAIL/DEV/OpenPype/.venv/lib/python3.7/site-packages/ftrack_api/collection.py", line 21, in <module>
    class Collection(collections.MutableSequence):

AttributeERROR: module 'collections' has no attribute 'MutableSequence'

********** ] ```
