### ISSUE TITLE
ModuleNotFoundERROR: No module named 'dataclasses'

### ISSUE THREAD

**Issue by Julm** [pypeclub/OpenPype#2888]
**Describe the bug**
Module dataclasses is not found, even though this library is a built-in since Python 3.7

**To Reproduce**

1. Add `from dataclasses import dataclass` in `openpype/__init__.py`
2. Build OpenPype
3. Run `openpype_gui.exe` or `openpype_console.exe`

**Desktop (please complete the following information):**
 - OS: Windows 10 Professional / build 19042.1586
 - OpenPype 3.8.2
 - Python 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)] (as `sys.version` tells)

**Additional context**
```
>>> run disk mapping command ...
*** Cannot get OpenPype path from database.
Finding latest version
  - booting version: 3.9.0
>>> Injecting OpenPype version to running environment  ...
>>> Validating version [ (...)\OpenPype\build\exe.win-amd64-3.7 ]
--- version is valid
>>> loading environments ...
  - for Avalon ...
Traceback (most recent call last):
  File "(...)\OpenPype\.venv\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 113, in run
    module_init.run(name + "__main__")
  File "(...)\OpenPype\.venv\Lib\site-packages\cx_Freeze\initscripts\Console.py", line 15, in run
    exec(code, module_main.__dict__)
  File "start.py", line 1146, in <module>
  File "start.py", line 1055, in boot
  File "start.py", line 330, in set_avalon_environments
  File "(...)\OpenPype\build\exe.win-amd64-3.7\openpype\__init__.py", line 8, in <module>
    from dataclasses import dataclass
ModuleNotFoundError: No module named 'dataclasses'
```

**Comment by Julm** [comment]
Add `"dataclasses"` to `install_requires` list in `./setup.py`
