### ISSUE TITLE
Maya: Create render instance with MayaSoftware

### ISSUE THREAD

**Issue by m-u-r-p-h-y** [pypeclub/OpenPype#3020]
**Describe the bug**
creating render instance in Maya scene with MayaSoftware as renderer

**To Reproduce**
1. open Maya file in lighting/lookdev context
2. make sure MayaSoftware is set as the render engine
3. Create a render instance

Failed to create Subset: "renderingMain" Family: "rendering" in Asset: "sh010"

```
Traceback (most recent call last):
  File "D:\REPO\OpenPype\openpype\tools\creator\window.py", line 435, in _on_create
    data={"variant": variant}
  File "D:\REPO\OpenPype\openpype\pipeline\create\legacy_create.py", line 152, in legacy_create
    instance = plugin.process()
  File "D:\REPO\OpenPype\openpype\hosts\maya\plugins\create\create_render.py", line 202, in process
    self._set_default_renderer_settings(renderer)
  File "D:\REPO\OpenPype\openpype\hosts\maya\plugins\create\create_render.py", line 429, in _set_default_renderer_settings
    prefix = self._image_prefixes[renderer]
KeyError: 'mayasoftware'

```

**Screenshots**

![image](https://user-images.githubusercontent.com/352795/161962756-5bb213ea-3dd3-4788-899e-40471d99cb1d.png)

**Comment by BigRoy** [comment]
I believe OpenPype doesn't have Maya Software render support so I believe this is unrelated to #3021 however it's a valid issue.

I think the error pop-up you get does show that it'd be nice if instead of failing with a code error that we raise an explicit error for a renderer if not supported.

Something along the lines of:
```python
if renderer not in self._image_prefixes:
    supported = ", ".join(self._image_prefixes.keys())
    raise CreatorError("Renderer is not supported: {} "
                       "(supported: {})".format(renderer, supported))
```

---

This particular issue would need a similar implementation to #2611 so I'm linking that purely as implementation reference.
