### ISSUE TITLE
Maya collect render fails when no render products are generated

### ISSUE THREAD

**Issue by antirotor** [pypeclub/OpenPype#3113]
## Bug

`collect_render` collector plugin in Maya will fail very ungracefully when conditions are so no render products are generated - for example frame range is set so, and so on. It should check if they are generated and if not then fail with specific error message. Currently the traceback doesn't say anything useful as it crashes on completely unrelated part of code.

**Comment by BigRoy** [comment]
Could you post the traceback/error that is seemingly unrelated?

Are you seeing this _No render cameras found._? Did you test with [this fix implemented](https://github.com/pypeclub/OpenPype/pull/3088)?

**Comment by BigRoy** [comment]
Or did you get this error:

**Message:** 
expected str, bytes or os.PathLike object, not NoneType

```
Traceback (most recent call last):
  File "S:\openpype\OpenPype\.venv\lib\site-packages\pyblish\plugin.py", line 522, in __explicit_process
    runner(*args)
  File "S:\openpype\OpenPype\openpype\hosts\maya\plugins\publish\collect_render.py", line 279, in process
  File "C:/Program Files/Autodesk/Maya2022\Python37\lib\ntpath.py", line 452, in normpath
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

I'm getting that when setting end frame to 1000 and start frame too 1001 (so start frame is lower than end frame, and thus NO frames are rendered).

**Comment by antirotor** [comment]
it fails sometimes before but the reason is probably the same:
```python
Traceback (most recent call last):
  File "C:\Program Files (x86)\OpenPype\dependencies\pyblish\plugin.py", line 522, in __explicit_process
    runner(*args)
  File "C:\Users\foo\AppData\Local\pypeclub\openpype\openpype-v3.9.5\openpype\hosts\maya\plugins\publish\collect_render.py", line 276, in process
  File "C:\Program Files\Autodesk\Maya2020\bin\python27.zip\ntpath.py", line 419, in normpath
    if path.startswith(('\\\\.\\', '\\\\?\\')):
AttributeError: 'NoneType' object has no attribute 'startswith'
```
