### ISSUE TITLE
UE5: rendering problem

### ISSUE THREAD

**Issue by antirotor** [pypeclub/OpenPype#3207]
It looks like render creator is not working in UE5:

```
Failed to create Subset: "renderUnrealProjectMain" Family: "render" in Asset: "TWDE"

Error: Array: Index 0 is out-of-bounds (len: 0) for property 'TransientPythonProperty' (ArrayProperty)

Traceback (most recent call last):
  File "C:\Users\artist\AppData\Local\pypeclub\openpype\openpype-v3.10.0-nightly.3+UE5patch\openpype\tools\creator\window.py", line 428, in _on_create
    legacy_create(
  File "C:\Users\artist\AppData\Local\pypeclub\openpype\openpype-v3.10.0-nightly.3+UE5patch\openpype\pipeline\create\legacy_create.py", line 157, in legacy_create
    instance = plugin.process()
  File "C:\Users\artist\AppData\Local\pypeclub\openpype\openpype-v3.10.0-nightly.3+UE5patch\openpype\hosts\unreal\plugins\create\create_render.py", line 32, in process
    ms = sequences[0].get_editor_property('object_path')
IndexError: Array: Index 0 is out-of-bounds (len: 0) for property 'TransientPythonProperty' (ArrayProperty)
```

[cuID:2b5rrkq]

**Comment by mkolar** [comment]
I believe this has been resolved by #3122 @simonebarbieri please let me know if that's not the case, and we'll reopen this
