### ISSUE TITLE
OP: OpenPypeTileAssembler not working in Deadline

### ISSUE THREAD

**Issue by m-u-r-p-h-y** [pypeclub/OpenPype#3451]
**Describe the bug**
Tile assembly job in Deadline is failing with following error

![image](https://user-images.githubusercontent.com/352795/176681390-aa26b281-d020-4529-af07-964fca78c0fd.png)

`WARNING: Python version for 'OpenPypeTileAssembler' plugin is not specified! Defaulting to Python 2.`

```
Error: ValueError : invalid literal for int() with base 10: '0.0' (Python.Runtime.PythonException)
  File "C:\ProgramData\Thinkbox\Deadline10\workers\WS01\plugins\62bd9a90407bd61ce47c3afd\OpenPypeTileAssembler.py", line 333, in render_argument
    "pos_x": int(data["Tile{}X".format(tile)]),
   at Python.Runtime.Dispatcher.Dispatch(ArrayList args)
   at __FranticX_GenericDelegate0`1\[\[System_String\, System_Private_CoreLib\, Version=4_0_0_0\, Culture=neutral\, PublicKeyToken=7cec85d7bea7798e\]\]Dispatcher.Invoke()
   at FranticX.Processes.ManagedProcess.RenderArgument()
   at Deadline.Plugins.DeadlinePlugin.RenderArgument()
   at FranticX.Processes.ManagedProcess.Execute(Boolean waitForExit)
   at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)
```

**To Reproduce**
Submit a Deadline Tile job with OpenPypeTileAssembler set for tiling assembly

**Comment by m-u-r-p-h-y** [comment]
The question is if we should not use the Draft plugin for assembling tiled renders by default, as it is not paid feature anymore.

Instead of maintaining OpenPypeTileAssembler . . .

**Comment by BigRoy** [comment]
> as it is not paid feature anymore.

I'd say if it's a solid feature of Deadline that works and isn't much more complex, is better or at least as good as the OpenImageIO setup then go for it. It'd mean maintaining less code.

Unless we want to stick with the OpenImageIO version so it's easier across multiple render manager implementations in the future, e.g. towards Muster/OpenCue (and/or there are other reasons for it)

**Comment by m-u-r-p-h-y** [comment]
You are right we have more farm managers, so the unified approach is the way to go . . .

**Comment by m-u-r-p-h-y** [comment]
So we need to rebuild the `OpenPypeTileAssembler` from the ground as it is not working. We are feeding it with data formatted for Draft plugin.

we also need to do some research on different renderers and the way they deal with tiled rendering (coordinate systems, offsets, etc.) and make it render farm manager agnostic.
