### ISSUE TITLE
publish to kitsu error

### ISSUE THREAD

**Issue by aramadan0096** [pypeclub/OpenPype#3528]
**Publish to kitsu error**
a bug stops the publishing to kitsu.

**To Reproduce**
1. Go to 'nuke studio'
2. Click on 'openpype menu'
3. Scroll down to 'publish'

**Expected behavior**
sucessful publishment.

**Screenshots**
![Screenshot 2022-07-18 015951](https://user-images.githubusercontent.com/57462754/179430431-d8542018-a9e0-4ac7-9441-b544fdc25c2c.png)
![Screenshot 2022-07-18 020035](https://user-images.githubusercontent.com/57462754/179430432-db144aa9-f7e4-43e3-b850-568236f15428.png)
![Screenshot 2022-07-18 020239](https://user-images.githubusercontent.com/57462754/179430434-16d50054-9f16-4ce3-8b98-e0d7aeb20986.png)
![Screenshot 2022-07-18 020258](https://user-images.githubusercontent.com/57462754/179430436-db829ee0-d54c-4a86-a385-8a492b3ae1c2.png)

**Desktop (please complete the following information):**
 - OS: [windows]
 - Host: [Nuke studio]

**Additional context**
errors files.
1.C:\Program Files (x86)\OpenPype\openpype\modules\kitsu\plugins\publish\integrate_kitsu_note.py

###

Message: 
'kitsu_task'
Line: 
26
Traceback: 
Traceback (most recent call last):
  File "C:\Program Files (x86)\OpenPype\dependencies\pyblish\plugin.py", line 522, in __explicit_process
    runner(*args)
  File "C:\Program Files (x86)\OpenPype\openpype\modules\kitsu\plugins\publish\integrate_kitsu_note.py", line 26, in process
KeyError: 'kitsu_task'
###

2.C:\Program Files (x86)\OpenPype\openpype\modules\kitsu\plugins\publish\integrate_kitsu_review.py

###

Instance: 
Video_1sq01sh060_shotMain
Message: 
'kitsu_task'
Line: 
17
Traceback: 
Traceback (most recent call last):
  File "C:\Program Files (x86)\OpenPype\dependencies\pyblish\plugin.py", line 522, in __explicit_process
    runner(*args)
  File "C:\Program Files (x86)\OpenPype\openpype\modules\kitsu\plugins\publish\integrate_kitsu_review.py", line 17, in process
KeyError: 'kitsu_task'
###

**Notice**
1.I'm using kitsu docker for testing
2.i've updated to the last 3 issues solve

[cuID:OP-3596]

**Comment by Tilix4** [comment]
Duplicated of https://github.com/pypeclub/OpenPype/issues/3552
