### ISSUE TITLE
Kitsu sync-service error

### ISSUE THREAD

**Issue by aramadan0096** [pypeclub/OpenPype#3635]
**Describe the bug**
Kitsu sync-service error.

**To Reproduce**
1. Running sync-service command
2. See error

**Expected behavior**
Importing all kitsu Projects.

```
Synchronizing Movie102...
Creating project 'Movie102'
!!! OpenPype crashed:
Traceback (most recent call last):
  File "start.py", line 1106, in boot
    _print("  - for modules ...")
  File "C:\Program Files (x86)\OpenPype\dependencies\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Program Files (x86)\OpenPype\dependencies\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Program Files (x86)\OpenPype\dependencies\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Program Files (x86)\OpenPype\dependencies\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Program Files (x86)\OpenPype\dependencies\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Program Files (x86)\OpenPype\dependencies\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Program Files (x86)\OpenPype\dependencies\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Program Files (x86)\OpenPype\openpype\modules\kitsu\kitsu_module.py", line 135, in sync_service
    sync_all_projects(login, password)
  File "C:\Program Files (x86)\OpenPype\openpype\modules\kitsu\utils\update_op_with_zou.py", line 338, in sync_all_projects
    sync_project_from_kitsu(dbcon, project)
  File "C:\Program Files (x86)\OpenPype\openpype\modules\kitsu\utils\update_op_with_zou.py", line 460, in sync_project_from_kitsu
    dbcon, project_doc, all_entities, zou_ids_and_asset_docs
  File "C:\Program Files (x86)\OpenPype\openpype\modules\kitsu\utils\update_op_with_zou.py", line 233, in update_op_assets
    item_name = f"{item_data['parents'][-1]}_{item['name']}"
IndexError: list index out of range
Press any key to continue . . .
```

**Desktop (please complete the following information):**
 - OS: [e.g. windows]
 - Host: [e.g. CMD]

**Additional context**
Openpype v3.13.0

**Comment by Tilix4** [comment]
It seems to fail only for non-TVshows project types.

**Comment by aramadan0096** [comment]
> It seems to fail only for non-TVshows project types.

Thanks for your quick response...
That's what I got after trying your last fix https://github.com/pypeclub/OpenPype/pull/3636/files


```
>>> run disk mapping command ...
>>> Logging to server is turned ON
*** Cannot get OpenPype path from database.
Finding latest version
  - booting version: 3.13.0
>>> Injecting OpenPype version to running environment  ...
>>> Validating version [ C:\Program Files (x86)\OpenPype ]
--- version is valid
>>> loading environments ...
  - for Avalon ...
  - global OpenPype ...
  - for modules ...
start.py:1119: MongoDeprecatedWarning: Call to deprecated function 'get_default_components'. Function was moved to 'openpype.client.mongo'.
  t_width = 20
start.py:1146: MongoDeprecatedWarning: Call to deprecated function 'get_default_components'. Function was moved to 'openpype.client.mongo'.
  from openpype.lib.log import Logger
*** OpenPype [ 3.13.0 ] ------------------------------------------------------------------------------------------------
>>> Using OpenPype from [  C:\Program Files (x86)\OpenPype  ]
... OpenPype variant:      [  production  ]
... Running OpenPype from: [  C:\Program Files (x86)\OpenPype  ]
... Using mongodb:         [  192.168.1.2  ]
... Logging to MongoDB:    [  192.168.1.2  ]
...   - port:              [  27017  ]
...   - database:          [  openpype  ]
...   - collection:        [  logs  ]
...   - user:              [  <N/A>  ]
!!! OpenPype crashed:
Traceback (most recent call last):
  File "start.py", line 1106, in boot
    _print("  - for modules ...")
  File "C:\Program Files (x86)\OpenPype\dependencies\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Program Files (x86)\OpenPype\dependencies\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Program Files (x86)\OpenPype\dependencies\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Program Files (x86)\OpenPype\dependencies\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Program Files (x86)\OpenPype\dependencies\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Program Files (x86)\OpenPype\dependencies\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Program Files (x86)\OpenPype\dependencies\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Program Files (x86)\OpenPype\openpype\modules\kitsu00\kitsu_module.py", line 135, in sync_service
    sync_all_projects(login, password)
  File "C:\Program Files (x86)\OpenPype\openpype\modules\kitsu00\utils\update_op_with_zou.py", line 328, in sync_all_projects
    if not validate_credentials(login, password):
  File "C:\Program Files (x86)\OpenPype\openpype\modules\kitsu\utils\credentials.py", line 27, in validate_credentials
    validate_host(kitsu_url)
  File "C:\Program Files (x86)\OpenPype\openpype\modules\kitsu\utils\credentials.py", line 54, in validate_host
    raise gazu.exception.HostException(f"Host '{kitsu_url}' is invalid.")
gazu.exception.HostException: Host 'None' is invalid.
Press any key to continue . . .
```

**Comment by Tilix4** [comment]
You should read the error message before sharing it ;)

The kitsu host URL you provided is `None`. Nothing to deal with my fix.

**Comment by aramadan0096** [comment]
> You should read the error message before sharing it ;)
> 
> The kitsu host URL you provided is `None`. Nothing to do with my fix.

Oops... you are right I've just noticed that my hole DB is droped
Thanks it works well
