### ISSUE TITLE
Maya: switching override_viewport_options OFF is crashing publish

### ISSUE THREAD

**Issue by m-u-r-p-h-y** [pypeclub/OpenPype#3752]
**Describe the bug**
switching `override_viewport_options`  off in  `project_settings/maya/publish/ExtractPlayblast/capture_preset/Viewport Options/override_viewport_options` is crashing publish

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/352795/187234006-f1dcacd8-a194-4569-bf05-883190ccb6b0.png)

```
// pyblish.ExtractPlayblast : Extracting capture.. // 
// pyblish.ExtractPlayblast : start: 991, end: 1070 // 
// pyblish.ExtractPlayblast : Outputting images to C:\Users\murph\AppData\Local\Temp\pyblish_tmp_tcprn7vv\reviewMain // 
// pyblish.ExtractPlayblast : using viewport preset: {'compression': 'jpg', 'format': 'image', 'quality': 95, 'off_screen': True, 'height': 1080, 'width': 1920, 'display_options': {'background': [0.49019607843137253, 0.49019607843137253, 0.49019607843137253], 'backgroundBottom': [0.49019607843137253, 0.49019607843137253, 0.49019607843137253], 'backgroundTop': [0.49019607843137253, 0.49019607843137253, 0.49019607843137253], 'displayGradient': True}, 'viewport_options': {'rendererName': 'vp2Renderer', 'displayLights': 'default', 'shadows': True, 'textures': True, 'twoSidedLighting': True, 'fogging': False, 'cameras': False, 'clipGhosts': False, 'controlVertices': False, 'deformers': False, 'dimensions': False, 'dynamicConstraints': False, 'dynamics': False, 'fluids': False, 'follicles': False, 'greasePencils': False, 'grid': False, 'hairSystems': True, 'handles': False, 'hud': True, 'hulls': False, 'ikHandles': False, 'imagePlane': True, 'joints': False, 'lights': False, 'locators': False, 'manipulators': False, 'motionTrails': False, 'nCloths': False, 'nParticles': False, 'nRigids': False, 'nurbsCurves': False, 'nurbsSurfaces': False, 'particleInstancers': False, 'pivots': False, 'planes': False, 'pluginShapes': False, 'polymeshes': True, 'strokes': False, 'subdivSurfaces': False}, 'viewport2_options': {'textureMaxResolution': 1024, 'enableTextureMaxRes': True, 'textureMaxResMode': 1, 'renderDepthOfField': True, 'lineAAEnable': True, 'multiSampleEnable': True, 'multiSampleCount': 8, 'ssaoEnable': False, 'ssaoAmount': 1, 'ssaoRadius': 16, 'ssaoFilterRadius': 16, 'ssaoSamples': 16, 'hwFogFalloff': 0, 'hwFogDensity': 0.0, 'hwFogStart': 0, 'hwFogEnd': 100, 'hwFogAlpha': 0, 'hwFogColorR': 1.0, 'hwFogColorG': 1.0, 'hwFogColorB': 1.0, 'motionBlurEnable': False, 'motionBlurSampleCount': 8, 'motionBlurShutterOpenFraction': 0.2}, 'sound': None, 'camera': '|camera1|cameraShape1', 'start_frame': 991, 'end_frame': 1070, 'filename': 'C:\\Users\\murph\\AppData\\Local\\Temp\\pyblish_tmp_tcprn7vv\\reviewMain', 'overwrite': True, 'viewer': False} // 
// Error: pyblish.plugin : Traceback (most recent call last):
  File "D:\REPO\OpenPype\.venv\lib\site-packages\pyblish\plugin.py", line 522, in __explicit_process
    runner(*args)
  File "D:\REPO\OpenPype\openpype\hosts\maya\plugins\publish\extract_playblast.py", line 131, in process
TypeError: Invalid flag 'with_focus'
Traceback (most recent call last):
  File "D:\REPO\OpenPype\.venv\lib\site-packages\pyblish\plugin.py", line 522, in __explicit_process
    runner(*args)
  File "<string>", line 131, in process
TypeError: Invalid flag 'with_focus' // 
```

**Comment by BigRoy** [comment]
The argument to [`maya.cmds.getPanel` should be `withFocus`](https://download.autodesk.com/us/maya/2010help/CommandsPython/getPanel.html#flagwithFocus) and not `with_focus`.
