### ISSUE TITLE
Maya: Vray Scene creator fails

### ISSUE THREAD

**Issue by m-u-r-p-h-y** [pypeclub/OpenPype#3796]
**Describe the bug**
Maya Vray Scene creator fails 

```

Failed to create Subset: "vraysceneMain" Family: "vrayscene" in Asset: "sh010"

Error: Unsupported type: <class 'dict_keys'>

Traceback (most recent call last):
  File "D:\REPO\OpenPype\openpype\tools\creator\window.py", line 432, in _on_create
    data={"variant": variant}
  File "D:\REPO\OpenPype\openpype\pipeline\create\legacy_create.py", line 196, in legacy_create
    instance = plugin.process()
  File "D:\REPO\OpenPype\openpype\hosts\maya\plugins\create\create_vrayscene.py", line 81, in process
    self.instance = super(CreateVRayScene, self).process()
  File "D:\REPO\OpenPype\openpype\hosts\maya\api\plugin.py", line 96, in process
    lib.imprint(instance, self.data)
  File "D:\REPO\OpenPype\openpype\hosts\maya\api\lib.py", line 426, in imprint
    raise TypeError("Unsupported type: %r" % type(value))
TypeError: Unsupported type: <class 'dict_keys'>
```

**Desktop (please complete the following information):**
 - OS: windows
 - Host: Maya 2022

**Comment by m-u-r-p-h-y** [comment]
Subsequently Vray scene collector fails as well


```
Instance: 
vraysceneMain
Message: 
'NoneType' object has no attribute 'group'
Line: 
50
Traceback: 
Traceback (most recent call last):
  File "D:\REPO\OpenPype\.venv\lib\site-packages\pyblish\plugin.py", line 522, in __explicit_process
    runner(*args)
  File "D:\REPO\OpenPype\openpype\hosts\maya\plugins\publish\collect_vrayscene.py", line 50, in process
AttributeError: 'NoneType' object has no attribute 'group'

```
