### ISSUE TITLE
Maya: Create VrayScene

### ISSUE THREAD

**Issue by m-u-r-p-h-y** [pypeclub/OpenPype#3808]
**Describe the bug**

Creating VrayScene instance in Maya is failing with an error:

```
Traceback (most recent call last):
  File "D:\REPO\OpenPype\openpype\tools\creator\window.py", line 432, in _on_create
    data={"variant": variant}
  File "D:\REPO\OpenPype\openpype\pipeline\create\legacy_create.py", line 196, in legacy_create
    instance = plugin.process()
  File "D:\REPO\OpenPype\openpype\hosts\maya\plugins\create\create_vrayscene.py", line 81, in process
    self.instance = super(CreateVRayScene, self).process()
  File "D:\REPO\OpenPype\openpype\hosts\maya\api\plugin.py", line 96, in process
    lib.imprint(instance, self.data)
  File "D:\REPO\OpenPype\openpype\hosts\maya\api\lib.py", line 426, in imprint
    raise TypeError("Unsupported type: %r" % type(value))
TypeError: Unsupported type: <class 'dict_keys'>
```

[cuID:2uc5a32]

**Comment by BigRoy** [comment]
Isn't this a **duplicate** of https://github.com/pypeclub/OpenPype/issues/3796 ?

**Comment by m-u-r-p-h-y** [comment]
yes it is. thx!
