### ISSUE TITLE
Conforming from Resolve18

### ISSUE THREAD

**Issue by aramadan0096** [pypeclub/OpenPype#3957]
**Running version**
3.14.1

**Describe the bug**
Unable to create shots from Resolve.

**To Reproduce**
1. Go to 'workspace'
2. Click on 'comp'
3. Scroll down to 'openpype menu'

**Expected behavior**
```
/Applications/OpenPype 3.14.1.app/Contents/MacOS/dependencies/qtpy/__init__.py:230: RuntimeWarning: Selected binding "pyqt5" could not be found, using "pyside2"
  'using "{}"'.format(initial_api, API), RuntimeWarning)
>>> [ openpype.hosts.resolve installed ]
>>> [ Registering DaVinci Resovle plug-ins.. ]
>>> [ Assigning resolve module to `pype.hosts.resolve.api.bmdvr`: Resolve (0x0x116ecb730) [App: 'Resolve' on 127.0.0.1, UUID: dd2ff155-c773-4f23-b6ec-e10c569bb4e7] ]
>>> [ Assigning resolve module to `pype.hosts.resolve.api.bmdvf`: FusionUI (0x0x149284210) [App: 'Resolve' on 127.0.0.1, UUID: dd2ff155-c773-4f23-b6ec-e10c569bb4e7] ]
Clicked Create
Using existing QApplication..
Failed to load path: "/Applications/OpenPype 3.14.1.app/Contents/MacOS/openpype/hosts/resolve/plugins/create/create_shot_clip.py"
Traceback (most recent call last):
  File "/Applications/OpenPype 3.14.1.app/Contents/MacOS/openpype/lib/python_module_tools.py", line 92, in modules_from_path
    module = import_filepath(full_path, mod_name)
  File "/Applications/OpenPype 3.14.1.app/Contents/MacOS/openpype/lib/python_module_tools.py", line 37, in import_filepath
    module_loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Applications/OpenPype 3.14.1.app/Contents/MacOS/openpype/hosts/resolve/plugins/create/create_shot_clip.py", line 9, in <module>
    class CreateShotClip(plugin.Creator):
  File "/Applications/OpenPype 3.14.1.app/Contents/MacOS/openpype/hosts/resolve/plugins/create/create_shot_clip.py", line 17, in CreateShotClip
    gui_tracks = get_video_track_names()
  File "/Applications/OpenPype 3.14.1.app/Contents/MacOS/openpype/hosts/resolve/api/lib.py", line 294, in get_video_track_names
    selected_track_count = timeline.GetTrackCount(track_type)
AttributeError: 'NoneType' object has no attribute 'GetTrackCount'
>>> [ *** Failed to load 1 files
- /Applications/OpenPype 3.14.1.app/Contents/MacOS/openpype/hosts/resolve/plugins/create/create_shot_clip.py
**********
Traceback (most recent call last):

  File "/Applications/OpenPype 3.14.1.app/Contents/MacOS/openpype/lib/python_module_tools.py", line 92, in modules_from_path
    module = import_filepath(full_path, mod_name)

  File "/Applications/OpenPype 3.14.1.app/Contents/MacOS/openpype/lib/python_module_tools.py", line 37, in import_filepath
    module_loader.exec_module(module)

  File "<frozen importlib._bootstrap_external>", line 728, in exec_module

  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "/Applications/OpenPype 3.14.1.app/Contents/MacOS/openpype/hosts/resolve/plugins/create/create_shot_clip.py", line 9, in <module>
    class CreateShotClip(plugin.Creator):

  File "/Applications/OpenPype 3.14.1.app/Contents/MacOS/openpype/hosts/resolve/plugins/create/create_shot_clip.py", line 17, in CreateShotClip
    gui_tracks = get_video_track_names()

  File "/Applications/OpenPype 3.14.1.app/Contents/MacOS/openpype/hosts/resolve/api/lib.py", line 294, in get_video_track_names
    selected_track_count = timeline.GetTrackCount(track_type)

AttributeError: 'NoneType' object has no attribute 'GetTrackCount'

********** ]
Registered font families: Noto Sans, Noto Sans, Noto Sans, Noto Sans, Noto Sans Mono, Noto Sans Mono, Noto Sans Mono, Noto Sans Mono, Noto Sans Mono, Noto Sans Mono, Noto Sans Mono, Noto Sans Mono, Noto Sans Mono
```

**Screenshots**
![Annotation 2022-10-11 013332.png](https://user-images.githubusercontent.com/57462754/194969880-811180a8-2d0f-4a8c-ad3d-1726d71b7e85.png)![Annotation 2022-10-11 005420.png](https://user-images.githubusercontent.com/57462754/194969896-30615c90-698a-48d3-ba2b-a571806454d3.png)![Annotation 2022-10-11 013427.png](https://user-images.githubusercontent.com/57462754/194969907-319a744c-cbd6-4599-8450-186bb2bef35a.png)

** (please complete the following information):**
 - OS: MacOS v12.5.1 Monterey
 - Host: Davinci Resolve 18.0.4

**Windows experience**
when I try to run it from windows I get this error
```
C:\Program Files (x86)\OpenPype\3.14.1\dependencies\qtpy\__init__.py:230: RuntimeWarning: Selected binding "pyqt5" could not be found, using "pyside2"
  'using "{}"'.format(initial_api, API), RuntimeWarning)
Traceback (most recent call last):
  File "C:\ProgramData\Blackmagic Design\DaVinci Resolve\Fusion\Scripts\Comp\__OpenPype__Menu__.py", line 20, in <module>
    result = main(os.environ)
  File "C:\ProgramData\Blackmagic Design\DaVinci Resolve\Fusion\Scripts\Comp\__OpenPype__Menu__.py", line 11, in main
    import openpype.hosts.resolve.api as bmdvr
  File "C:\Program Files (x86)\OpenPype\3.14.1\openpype\hosts\resolve\api\__init__.py", line 12, in <module>
    from .pipeline import (
  File "C:\Program Files (x86)\OpenPype\3.14.1\openpype\hosts\resolve\api\pipeline.py", line 21, in <module>
    from . import lib
  File "C:\Users\ahmed.ramadan\AppData\Local\Programs\Python\Python36\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Program Files (x86)\OpenPype\3.14.1\openpype\hosts\resolve\api\lib.py", line 6, in <module>
    from opentimelineio import opentime
  File "C:\Users\ahmed.ramadan\AppData\Local\Programs\Python\Python36\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Program Files (x86)\OpenPype\3.14.1\dependencies\opentimelineio\__init__.py", line 35, in <module>
    from . import (
  File "C:\Users\ahmed.ramadan\AppData\Local\Programs\Python\Python36\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Program Files (x86)\OpenPype\3.14.1\dependencies\opentimelineio\opentime.py", line 1, in <module>
    from . _opentime import ( # noqa
  File "C:\Users\ahmed.ramadan\AppData\Local\Programs\Python\Python36\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'opentimelineio._opentime'
```

[cuID:OP-4216]

**Comment by jakubjezek001** [comment]
Hey @aramadan0096 thanks for the report. Yeah I believe there is the issue with updated API. Resolve is always doing this version to version. 

We will need to update the api to the latest changes.

**Comment by aramadan0096** [comment]
> Hey @aramadan0096 thanks for the report. Yeah I believe there is the issue with updated API. Resolve is always doing this version to version. 
> 
> We will need to update the api to the latest changes. 
> 

Hey @jakubjezek001 thanks for replying...
I believe that Resolve has the worst API and scripting case in all DCC ever, but actually it has many strengths versus Hiero such as speed and colorspace handling... That's why I hope to run it with OpenPype
