### ISSUE TITLE
Maya: Extract Layout more than one container found

### ISSUE THREAD

**Issue by m-u-r-p-h-y** [pypeclub/OpenPype#4030]
**Running version**
3.14.4

**Describe the bug**
Layout publish is broken

**To Reproduce**

Publish Layout

**Screenshots**
![image](https://user-images.githubusercontent.com/352795/197957961-d2c66f55-abee-4b7b-ab21-5f96c8772184.png)

**Desktop (please complete the following information):**
 - OS: windows
 - Host: Maya

**Additional context**
```
Message: 
More than one container found for pTorus1
Line: 
39
Traceback: 
Traceback (most recent call last):
  File "D:\REPO\OpenPype\.venv\lib\site-packages\pyblish\plugin.py", line 522, in __explicit_process
    runner(*args)
  File "D:\REPO\OpenPype\openpype\hosts\maya\plugins\publish\extract_layout.py", line 39, in process
AssertionError: More than one container found for pTorus1
```

[cuID:30m9hu8]

**Comment by BigRoy** [comment]
Was this issue resolved with PR https://github.com/ynput/OpenPype/pull/4098 ?
