### ISSUE TITLE
Maya: 2020/2022 extract playblast

### ISSUE THREAD

**Issue by m-u-r-p-h-y** [pypeclub/OpenPype#4033]
**Running version**
3.14.5

Maya2020
Maya2022 and Maya 2023 does not suffer from this issue

**Screenshots**
![image](https://user-images.githubusercontent.com/352795/198026273-ebf557a5-f481-469e-8775-0b5b9a4f84fb.png)

**Desktop (please complete the following information):**
 - OS: windows
 - Host: Maya 2020

**Additional context**
```
Instance: 
modelMain
Message: 
Invalid flag ''
Line: 
739
Traceback: 
Traceback (most recent call last):
  File "D:\REPO\OpenPype\.venv\lib\site-packages\pyblish\plugin.py", line 522, in __explicit_process
    runner(*args)
  File "D:\REPO\OpenPype\openpype\hosts\maya\plugins\publish\extract_playblast.py", line 136, in process
  File "D:\REPO\OpenPype\openpype\vendor\python\common\capture.py", line 199, in capture
    _maintained_time()
  File "C:\Program Files\Autodesk\Maya2020\bin\python27.zip\contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "C:\Program Files\Autodesk\Maya2020\bin\python27.zip\contextlib.py", line 112, in nested
    vars.append(enter())
  File "C:\Program Files\Autodesk\Maya2020\bin\python27.zip\contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "D:\REPO\OpenPype\openpype\vendor\python\common\capture.py", line 739, in _applied_viewport_options
    cmds.modelEditor(panel, edit=True, **options)
TypeError: Invalid flag ''
```

[cuID:OP-4316]

**Comment by BigRoy** [comment]
This particular flag will only exist if `gpuCache.mll` is loaded. Could it be related to that? :)

**Comment by m-u-r-p-h-y** [comment]
the first one seems like a typo though  . . .

**Comment by m-u-r-p-h-y** [comment]
> Maybe this particular flag will only exist if `gpuCache.mll` is loaded. Could it be related to that? :)
> 
 or maybe the opposite way. If it is NOT loaded.
